In [8]:
import torch
input = torch.rand(2,2)
input

tensor([[0.4804, 0.6712],
        [0.9949, 0.0817]])

In [9]:
Q = torch.quantize_per_tensor(input,scale = 0.025 , zero_point = 0, dtype = torch.quint8)
Q

tensor([[0.4750, 0.6750],
        [1.0000, 0.0750]], size=(2, 2), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.025, zero_point=0)

In [10]:
Q.dequantize()

tensor([[0.4750, 0.6750],
        [1.0000, 0.0750]])